# backend-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: backend
  namespace: argocd

  annotations:

    argocd-image-updater.argoproj.io/image-list: backend=jatin44/obs-backend

    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository

    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag

    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build

    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/malhotra-jatin44/cicd-3-tier-message-app.git
    targetRevision: main
    path: k8s/backend-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: messaging-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true