# frontend-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: frontend
  namespace: argocd

  annotations:

    argocd-image-updater.argoproj.io/image-list: frontend=jatin44/obs-frontend

    argocd-image-updater.argoproj.io/frontend.helm.image-name: image.repository

    argocd-image-updater.argoproj.io/frontend.helm.image-tag: image.tag

    argocd-image-updater.argoproj.io/frontend.update-strategy: latest

    argocd-image-updater.argoproj.io/write-back-method: git

    argocd-image-updater.argoproj.io/git-branch: main

    argocd-image-updater.argoproj.io/write-back-target: helmvalues

    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^main-[a-f0-9]+$

spec:
  project: default

  source:
    repoURL: https://github.com/malhotra-jatin44/cicd-3-tier-message-app.git
    targetRevision: main
    path: k8s/frontend-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: messaging-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true